[package]
name = "rgrep"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"

[[bin]]
edition = "2018"
name = "rgrep"
path = "src/main.rs"
